### ISSUE TITLE
Kaspersky antivirus removes this app

### ISSUE THREAD

**Issue by sindzicat** [AsishRaju/HotCorners#1]
Hello.
Just after installation Kaspersky removed this app.
It found something like trojan.

**Comment by AsishRaju** [comment]
which version have u downloaded?
did u try HotCornersV1.2.0  [Here](https://sourceforge.net/projects/hotcorners/files/HotCornersSetup_V1.2.exe/download)

**Comment by sindzicat** [comment]
Yes, I installed version 1.2.0.

**Comment by AsishRaju** [comment]
This issue is rarely seen in few antivirus software which u can check them [here](https://www.virustotal.com/gui/file/632919a65b60c96dc8359fe153305f41973bc4bb54d8a655f24bca3a9bc3d3ea/detection), but i can assure there is no virus/torjan that is included with this . but u can always use the dist folder from the repo and manually run the jar file .
